version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"  # Expose port 8080 on the host to port 80 on the container
    volumes:
      - .:/var/www/html  # Mount the current directory to the container's web root
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root user password
      MYSQL_DATABASE: user_db        # Database name
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for automatic execution
    ports:
      - "3306:3306"  # Expose MySQL port
    networks:
      - default

volumes:
  db_data:

networks:
  default:
