version: '4.34'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Access phpMyAdmin via http://localhost:8081
    environment:
      PMA_HOST: db  # MySQL service name for phpMyAdmin
    depends_on:
      - db
    networks:
      - default

  web:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"  # Access web app via http://localhost:8080
    volumes:
      - .:/var/www/html  # Mount the current directory to the container's web root
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root user password
      MYSQL_DATABASE: user_db             # Database name
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for automatic execution
    ports:
      - "3306:3306"  # Expose MySQL port
    networks:
      - default

volumes:
  db_data:

networks:
  default:
